# 这些是 GitHub 赞助者的支持链接。最多可以添加四个链接，GitHub 将在仓库顶部显示一个赞助者按钮。

github: [zyuanhua] # 用逗号分隔多个用户名
patreon: # 用逗号分隔多个用户名
open_collective: # 用逗号分隔多个用户名
ko_fi: # 用逗号分隔多个用户名
tidelift: # 用逗号分隔多个用户名
community_bridge: # 用逗号分隔多个用户名
liberapay: # 用逗号分隔多个用户名
issuehunt: # 用逗号分隔多个用户名
otechie: # 用逗号分隔多个用户名
custom: # 用逗号分隔多个自定义链接